site_name: DictatorGen AI Documentation
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google  # Supporte aussi numpy ou reStructuredText
